[application]

# App (Project) Name
name = "Ifecaro"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Ifecaro"

# Favicon settings
favicon = "/favicon.ico"
apple_touch_icon = "/img/icons/apple-touch-icon.png"
android_chrome_192 = "/img/icons/android-chrome-192x192.png"
android_chrome_512 = "/img/icons/android-chrome-512x512.png"
manifest = "manifest.json"

# HTML head 設定
head = """
    <link rel="modulepreload" href="/assets/dioxus/Ifecaro-Engine.js">
    <link rel="preload" href="/assets/dioxus/Ifecaro-Engine_bg.wasm" as="fetch" crossorigin>
    <link rel="preload" href="/public/fonts/NotoSansTC-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="manifest" href="manifest.json">
    <meta name="theme-color" content="#000000">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Ifecaro">
"""

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# uncomment line below if using Router
index_on_404 = true
